from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

MODE = "TEST"
ABORT_ALL = False
FIND_COINTEGRATED = True
PLACE_TRADES = True
FIND_EXITS = True

RESOLUTION = "1HOUR"
WINDOW = 21
MAX_HALF_LIFE = 24
ZSCORE_THRESHOLD = 1.5
USD_PER_TRADE = 75
USD_MIN_COLLATERAL = 1880
CLOSE_AT_ZSCORE_CROSS = True

ETH_ADDR = "0x55c9269A17E7bB73b899F09066aee44841874cAA"

STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET") 
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "MAIN" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "MAIN" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "MAIN" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "MAIN" else DYDX_API_PASSPHRASE_TESTNET

HOST = API_HOST_MAINNET if MODE == "MAIN" else API_HOST_GOERLI

HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/MEwqIDI44J8UGxHuZ6Tm15EbhqRdPoce"
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/Y2Z2cHSSY-2iG_kceh1TK55JzzTv6hsr"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "MAIN" else HTTP_PROVIDER_TESTNET